## Viwing Arrays and Matrices

In [2]:
import numpy as np

In [3]:
sample_array = np.random.randint(0, 10, size = (3,3))
sample_array

array([[2, 1, 1],
       [2, 7, 0],
       [4, 0, 8]])

In [4]:
#to find out the unique numbers from that array
np.unique(sample_array)

array([0, 1, 2, 4, 7, 8])

In [5]:
#let's create some arrays as we did previously
a1 = np.array([1,2,3])

In [6]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])

In [7]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
              [16, 17, 18]]])

In [8]:
#what if we want to return the first index of each arrays
a1[0]

1

In [9]:
a2[0]

array([1. , 2. , 3.3])

In [10]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#see this is returning all the values at index 0 based on their dimensions
#for a1 array as its 1 dimension and a vector so it returns just the first number
#but for a2 and a3 as they are multi-dimensional matrices they return the array value at the index

In [12]:
#we can also slice the matrices like Python list
a1[:2]

array([1, 2])

In [13]:
a2[:1]

array([[1. , 2. , 3.3]])

In [14]:
a3.ndim

3

In [15]:
#as a3 array is multi-dimensional we need to slice it in a different way
#as a2 is 2 3 3 dimensional that's why you need to put values for each parameter to slice it
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [16]:
#lets create more complex array
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 8, 7, 4, 9],
         [1, 1, 0, 5, 8],
         [1, 3, 3, 4, 0],
         [7, 4, 7, 1, 9]],

        [[6, 4, 0, 2, 0],
         [1, 8, 2, 1, 2],
         [3, 8, 2, 0, 1],
         [3, 6, 9, 5, 0]],

        [[3, 4, 2, 2, 6],
         [9, 7, 1, 4, 8],
         [8, 7, 6, 4, 4],
         [7, 3, 6, 2, 5]]],


       [[[6, 0, 7, 3, 0],
         [5, 4, 1, 7, 3],
         [0, 0, 0, 6, 9],
         [2, 7, 0, 8, 3]],

        [[7, 6, 7, 2, 5],
         [6, 7, 2, 9, 9],
         [0, 4, 1, 1, 3],
         [8, 2, 1, 9, 4]],

        [[7, 8, 5, 7, 7],
         [4, 9, 6, 1, 6],
         [9, 2, 1, 1, 1],
         [3, 7, 6, 1, 0]]]])

In [17]:
#now if we check its dimensions
a3.shape, a4.ndim

((2, 3, 3), 4)

In [18]:
#you will see it as a 4-dimensional array. Now if we want to slice it we will have to include parameters accoring to its size
a4[:, :, :, :2]

array([[[[3, 8],
         [1, 1],
         [1, 3],
         [7, 4]],

        [[6, 4],
         [1, 8],
         [3, 8],
         [3, 6]],

        [[3, 4],
         [9, 7],
         [8, 7],
         [7, 3]]],


       [[[6, 0],
         [5, 4],
         [0, 0],
         [2, 7]],

        [[7, 6],
         [6, 7],
         [0, 4],
         [8, 2]],

        [[7, 8],
         [4, 9],
         [9, 2],
         [3, 7]]]])

In [19]:
#that's how we can view our matrices in different ways