In [1]:
import numpy  as np

In [3]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
              [16, 17, 18]]])

In [9]:
#if we try to multiply this two arrays you will see an error 
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [11]:
#this error occurs because of the arrays being of different shape

In [17]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [19]:
#reassign it to a new variable
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [21]:
#now if we try to do the multiplication you will see a successful output
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
#we will now use transpose 
a2.