## Comparison Opeartors

import numpy as np

In [3]:
a1 = np.array([1,2,3])

In [5]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])

In [7]:
#Now if we start to compare
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [9]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [11]:
a1 < a2

array([[False, False,  True],
       [ True,  True,  True]])

In [13]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [15]:
a1 < 5

array([ True,  True,  True])

## Sorting Arrays

In [21]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[2, 9, 0, 7, 8],
       [0, 3, 0, 1, 3],
       [9, 7, 4, 7, 9]])

In [23]:
np.sort(random_array)

array([[0, 2, 7, 8, 9],
       [0, 0, 1, 3, 3],
       [4, 7, 7, 9, 9]])

In [25]:
np.argsort(random_array)

array([[2, 0, 3, 4, 1],
       [0, 2, 3, 1, 4],
       [2, 1, 3, 0, 4]], dtype=int64)