## Creating Arrays

In [2]:
import numpy as np

In [3]:
ones = np.ones((2,3))
#so this function returns us an array filled with 1 in the shape of 2,3
#if you press shift+tab you'd know more about this funcitons
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
#similarly we can do this with zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [6]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[3, 1, 4, 5, 7],
       [0, 5, 9, 4, 9],
       [8, 2, 7, 2, 0]])

In [7]:
random_array2 = np.random.random((3,5))
random_array2

array([[0.0425793 , 0.6219145 , 0.69154178, 0.82171472, 0.33651978],
       [0.06323917, 0.04062435, 0.09569396, 0.28648051, 0.60435051],
       [0.73532619, 0.79508539, 0.18912279, 0.88843572, 0.52065079]])

In [38]:
random_array3 = np.random.rand(3,5)
random_array3

array([[0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837],
       [0.13316945, 0.52341258, 0.75040986, 0.66901324, 0.46775286]])

In [42]:
# to use random numbers, but they will be the same after running multiple times.
#we can use the seed function

np.random.seed(7)
random_array4 = np.random.rand(3,5)
random_array4

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ]])

In [ ]:
#now you'd see even if i run the cell 1000 times the values of the array won't change