## Creating Arrays

In [4]:
import numpy as np

In [10]:
ones = np.ones((2,3))
#so this function returns us an array filled with 1 in the shape of 2,3
#if you press shift+tab you'd know more about this funcitons
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#similarly we can do this with zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 7, 9, 5, 8],
       [6, 4, 4, 2, 9],
       [6, 2, 4, 7, 9]])

In [20]:
random_array2 = np.random.random((3,5))
random_array2

array([[0.28607227, 0.84795523, 0.2663838 , 0.59961308, 0.90548019],
       [0.3029023 , 0.05254982, 0.47057082, 0.80474838, 0.67174929],
       [0.7188403 , 0.67985777, 0.85319847, 0.02067721, 0.34624473]])

In [22]:
random_array3 = np.random.rand(3,5)
random_array3

array([[0.16629934, 0.78854713, 0.45822038, 0.65510696, 0.13247236],
       [0.00672382, 0.08113287, 0.97797774, 0.13863982, 0.95511844],
       [0.40590709, 0.49825163, 0.552838  , 0.94120752, 0.35477522]])