## Dot Product Example

In [2]:
import numpy as np

In [3]:
np.random.seed(0)
#Creating Numbers of Jars sold randomly

sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [4]:
#Now we will create a Dataframe
#for that we will need the help of Pandas
import pandas as pd
weekly_sales = pd.DataFrame(sales_amount, 
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [5]:
#creating prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [6]:
#now, we will turn this into a data frame as well
butter_prices = pd.DataFrame(prices.reshape(1,3),  index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [7]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [13]:
#so as the shapes are not aligned so what we need to do? we need to transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [15]:
#create dai;y_sales
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [17]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [19]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [21]:
#now we need to add it to the new column
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [23]:

weekly_sales["Total Sale"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total Sale

In [25]:
#this doesn't work because we are getting into another shape error
#so we need to transpose here as well
weekly_sales["Total Sales"] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142