## Manipulating and Comparing Arrays

### Arithmetic

In [3]:
import numpy as np

In [5]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [9]:
a1 + ones

array([2., 3., 4.])

In [11]:
a1 - ones

array([0., 1., 2.])

In [13]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [35]:
#multiplying a1 array with a2
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [36]:
#let's try to do some more complex ones
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
              [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
# you'd see this will through us an error
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [21]:
#so now we will try and learn something new 
# so that we can change the shape of this array so that they can be compatible
# we will look into it in the future for now we will only look into basic operations

In [23]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [31]:
#we can also round it
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [29]:
# we can also use power
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [41]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [43]:
# we can do all these opeations using numpy functions as well
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.add(a1, a2)

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])